EXTENSION_DIR=$(DESTDIR)/usr/lib/surfer
CC=gcc
CFLAGS += -Wall -Wextra -Wno-unused-parameter -O3


.PHONY: all clear install installdirs 



all:surfer adblock.so

reinstall:install
	rm -f /usr/share/surfer/black.css

	

surfer: surfer.c
	$(CC) -o $@ $^ $(CFLAGS) -o surfer `pkg-config --cflags --libs gtk+-3.0 glib-2.0 webkit2gtk-4.0`\



web_extension/asdf.c.lo: web_extension/asdf.c
  libtool --mode=compile --tag=CC $(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@


web_extension/libasdf.la: web_extension/asdf.c.lo 
  libtool --mode=link --tag=CC $(CC) -o $@ $< -rpath $(INSTALLDIR)/lib/surfer/web_extension \
  -module -avoid-version -no-undefined


installdirs:

	install -d $(INSTALLDIR)/lib
	install -d $(INSTALLDIR)/lib/luakit

	install -m0644 web-extension/.libs/libasdf.so $(INSTALLDIR)/lib/luakit/web-extensions
  install -d $(INSTALLDIR)/lib/luakit/web-extensions	install -Dm755 surfer $(DESTDIR)/usr/bin/surfer

	install -Dm644 surfer.desktop $(DESTDIR)/usr/share/applications/surfer.desktop
	install -Dm644 surfer.1 $(DESTDIR)/usr/share/man/man1/surfer.1
	install -Dm644 black.css $(DESTDIR)/usr/share/surfer/black.css
