.TH lariza 1 "2015-11-28" "lariza" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
surfer \- basic  webkit2gtk browser
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBsurfer\fP is a simple web browser,keyboard based, using GTK+ 3 and WebKit2GTK+.
.\" --------------------------------------------------------------------

.SH SHORTCUTS

For actual list of shortcuts/keys refer to page of project http://github.com/nihilowy/surfer
.\" --------------------------------------------------------------------

.SH FILES
File created in your home dir:
.fav - file with bookmarks
.cookies - directory for cookies
.\" --------------------------------------------------------------------
.SH LICENSE
\fBsurfer\fP is on GPL license.
