.TH surfer 1 "2017-1-1" "surfer" "User Commands"
.\" ---------------------------------------------------------------------------
.SH NAME
surfer \- simple keyboard based webkit browser
.\" ---------------------------------------------------------------------------
.SH DESCRIPTION
\fBsurfer\fP is a simple web browser,keyboard based.

 For videos install gstreamer packages. 

 config.h - customize keys, dirs and some other settings before compile. 

 It can also launch mpv( with help of youtube-dl on supported sites) on links,
 but remember to pkill -9 mpv if it hogs your cpu, used on non supported sites.
 
 Beside it can toggle JS and History. Priv mode. You can also set css for sites in .surfer/tablecss.txt file. 
 
 Search or translate for selected text, settable in config.h 

 For adblock:
 Install https://github.com/jun7/wyebadblock
 Then sudo ln -s /usr/lib/wyebrowser/adblock.so /usr/lib/surfer

 Or block through /etc/hosts

 Or save to .surfer/adblock.json file (ie from https://easylist-downloads.adblockplus.org/easylist_min_content_blocker.json )


 For JS scripts:

 Js scripts (i.e. from  greasefork site) place in .local/share/surfer/

 name them in following way:
 -i.e. for run scripts on www.youtube.com name script file identically.
 -if you want script to run on all sites, name it universal.js

.\" ---------------------------------------------------------------------------

.SH SHORTCUTS

\fBCtrl + click\fP open link in new window

\fBCtrl + n\fP     new window

\fBCtrl + b\fP     go back

\fBCtrl + f\fP     go forward

\fBCtrl + q\fP     quit

\fBEsc\fP          stop loading

\fBCtrl + h\fP     home (bookmarks list)

\fBCtrl + o\fP     toggle url bar

\fBCtrl + /\fP     find word

\fBCtrl + r\fP     reload page

\fBCtrl + =\fP     zoom in

\fBCtrl + -\fP     zoom out

\fBDown Arrow\fP   scroll down

\fBUp arrow\fP     scroll up

\fBCtrl +  w\fP    page up 

\fBCtrl +  s\fP    page down

\fBF11\fP          toggle fullscreen

\fBCtrl + shift + b\fP  bookmark site (to remove just edit file with links: fav in your SURFER_DIR dir)

\fBCtrl + Shift + i\fP  web inspector (page source)

\fBCtrl + Shift + s\fP  toggle user style black theme (/usr/share/surfer/black.css)

\fBCtrl + Shift + h\fP  show history if enabled

Also refer to page of project http://github.com/nihilowy/surfer

.\" --------------------------------------------------------------------

.SH FILES
Files created in your home dir:
.TP
 SURFER_DIR/fav - file with bookmarks ( added with ctrl + shift + b, edit if You like to remove any )
.TP
 SURFER_DIR/cookies - file for cookies
.TP
 .cache - directory for cached content, localstorage and databases are in .local/share/webkitgtk
.TP
 SURFER_DIR/hist - file for history if enabled in surfer.c
.TP
 SURFER_DIR/tablecss.txt - file for setting css for site
.TP
 SURFER_DOWNLOADS - dir for downloads with SURFER_DIR customizable in config.h
.\" --------------------------------------------------------------------
.SH LICENSE
\fBsurfer\fP is on GPL 3.0 license.
